<a href="https://colab.research.google.com/github/harshi3-code/cnn1-harshi/blob/main/ICP2cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Harshitha Gontu
700766967
2024 Fall CS-5720: Neural Network & Deep Learning

In [6]:
class Employee:
    # Class variable to count the number of Employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        # Instance variables
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        # Increment the employee count when a new instance is created
        Employee.employee_count += 1

    @classmethod
    def average_salary(cls, employees):
        # Calculate average salary of given list of employees
        if not employees:
            return 0
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / len(employees)

    def display_employee(self):
        # Method to display employee details
        return (f"Name: {self.name}, Family: {self.family}, Salary: {self.salary}, "
                f"Department: {self.department}")

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        # Initialize base class
        super().__init__(name, family, salary, department)
        self.benefits = benefits

    def display_fulltime_employee(self):
        # Method to display full-time employee details including benefits
        return (f"{super().display_employee()}, Benefits: {self.benefits}")

# Create instances of Employee
emp1 = Employee("Geetha", "arav Family", 52000, "Engineering")
emp2 = Employee("Seetha", "kutty Family", 62000, "Marketing")

# Create instances of FulltimeEmployee
ft_emp1 = FulltimeEmployee("Alita", "Johnson Family", 72000, "Finance", "Health Insurance")
ft_emp2 = FulltimeEmployee("Bob", "marvel Family", 92000, "IT", "Dental Insurance")

# List of all employees for average salary calculation
employees = [emp1, emp2, ft_emp1, ft_emp2]

# Display employee details and average salary
print(emp1.display_employee())
print(emp2.display_employee())
print(ft_emp1.display_fulltime_employee())
print(ft_emp2.display_fulltime_employee())

# Calculate and display average salary
avg_salary = Employee.average_salary(employees)
print(f"Average Salary: {avg_salary}")

# Display total number of employees
print(f"Total Number of Employees: {Employee.employee_count}")


Name: Geetha, Family: arav Family, Salary: 52000, Department: Engineering
Name: Seetha, Family: kutty Family, Salary: 62000, Department: Marketing
Name: Alita, Family: Johnson Family, Salary: 72000, Department: Finance, Benefits: Health Insurance
Name: Bob, Family: marvel Family, Salary: 92000, Department: IT, Benefits: Dental Insurance
Average Salary: 69500.0
Total Number of Employees: 4


In [8]:
class Employee:
    # Class variable to count the number of employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        # Instance variables
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        # Increment the employee count when a new instance is created
        Employee.employee_count += 1

    @classmethod
    def average_salary(cls, employees):
        """Calculate the average salary of a list of employees."""
        if not employees:
            return 0
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / len(employees)

    def display_employee(self):
        """Return a string representation of the employee's details."""
        return (f"Name: {self.name}, Family: {self.family}, Salary: {self.salary}, "
                f"Department: {self.department}")

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        # Initialize the base class (Employee)
        super().__init__(name, family, salary, department)
        self.benefits = benefits

    def display_fulltime_employee(self):
        """Return a string representation of the full-time employee's details including benefits."""
        return (f"{super().display_employee()}, Benefits: {self.benefits}")

# Create instances of Employee
emp1 = Employee("Joe", "Doe Family", 65000, "Engineering")
emp2 = Employee("Mith", "Smith Family", 89000, "Marketing")

# Create instances of FulltimeEmployee
ft_emp1 = FulltimeEmployee("Johnson", "John Family", 85000, "Finance", "Health Insurance")
ft_emp2 = FulltimeEmployee("Brook", "Bro Family", 85400, "IT", "Dental Insurance")

# List of all employees for average salary calculation
employees = [emp1, emp2, ft_emp1, ft_emp2]

# Display employee details and average salary
print(emp1.display_employee())
print(emp2.display_employee())
print(ft_emp1.display_fulltime_employee())
print(ft_emp2.display_fulltime_employee())

# Calculate and display average salary
avg_salary = Employee.average_salary(employees)
print(f"Average Salary: {avg_salary}")

# Display total number of employees
print(f"Total Number of Employees: {Employee.employee_count}")


Name: Joe, Family: Doe Family, Salary: 65000, Department: Engineering
Name: Mith, Family: Smith Family, Salary: 89000, Department: Marketing
Name: Johnson, Family: John Family, Salary: 85000, Department: Finance, Benefits: Health Insurance
Name: Brook, Family: Bro Family, Salary: 85400, Department: IT, Benefits: Dental Insurance
Average Salary: 81100.0
Total Number of Employees: 4


In [7]:
import numpy as np

# Step 1: Create a random vector of size 20 with values in the range 1-20
vector = np.random.uniform(1, 20, 20)

# Step 2: Reshape the vector to a 4x5 matrix
matrix = vector.reshape(4, 5)

# Step 3: Replace the maximum value in each row with 0
# Find the indices of the maximum values in each row
max_indices = np.argmax(matrix, axis=1)
# Use broadcasting to set these maximum values to 0
matrix[np.arange(matrix.shape[0]), max_indices] = 0

# Print the resulting matrix
print("Original matrix with max values replaced by 0:")
print(matrix)


Original matrix with max values replaced by 0:
[[ 4.87025576  0.         12.45880878 15.0790757   7.71167395]
 [18.12449714  0.          5.27784889 12.48427847 14.45778711]
 [13.10369031  9.64653409  3.20653264 13.40803688  0.        ]
 [14.8498511   0.          6.16825472 13.05816819  5.72004744]]
